version: "26"
services:
  app:
    build: .
    ports:
      - 3000:3000
    working_dir: /src
    volumes:
      - ./:/src
    depends_on:
      - db
  db:
    image: "root/docker-sql:initial"
    ports:
      - 1433:1433
    environment:
      SA_PASSWORD: "Mikrobiol2162"
      ACCEPT_EULA: "Y"
    volumes:
      - mssql-data:/var/opt/mssql

volumes:
  mssql-data: