version: '3.8'
services:
  hasura:
    image: hasura/graphql-engine:v2.31.0 
    container_name: hasura
    ports:
      - "80:8080"
    environment:
      HASURA_GRAPHQL_DATABASE_URL: mysql://sql7732050:Uu3izeb3Ac@sql7.freesqldatabase.com:3306/sql7732050
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" 
      HASURA_GRAPHQL_ADMIN_SECRET: adminkey123
    restart: always
    # depends_on:
    #   - mysql # not using local MySQL container in production

  # for testing
  # mysql:
  #   image: mysql:8.0
  #   container_name: mysql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: <root_password>
  #     MYSQL_DATABASE: <database_name>
  #     MYSQL_USER: <user_name>
  #     MYSQL_PASSWORD: <password>
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - mysql_data:/var/lib/mysql

# volumes:
#   mysql_data: 
