version: "26"
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Mikrobiol2162"
    volumes:
      - mssql-data:/var/opt/mssql
  graphql-engine:
    image: hasura/graphql-engine:v2.39.0
    ports:
      - "4000:8080"
    depends_on:
      - "mssql"
    restart: always
    environment:
      MSSQL_DATABASE_URL: Driver=msodbcsql18;Server=tcp:mssql,1433;Database=SQL_DB;Uid=SA;Pwd=Mikrobiol2162;Encrypt=optional
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
  postgres:
      image: postgres:15
      restart: always
      volumes:
        - db_data:/var/lib/postgresql/data
      environment:
        POSTGRES_PASSWORD: postgrespassword
volumes:
  mssql-data:
  db_data: