name: Trigger auto deployment for health-center

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/health-center-AutoDeployTrigger-bc6d0839-3cd3-4cfc-8984-d2f3b7ada335.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.HEALTHCENTER_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.HEALTHCENTER_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.HEALTHCENTER_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: appenvironment128212.azurecr.io
          registryUsername: ${{ secrets.HEALTHCENTER_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.HEALTHCENTER_REGISTRY_PASSWORD }}
          containerAppName: health-center
          resourceGroup: app-environment
          imageToBuild: appenvironment128212.azurecr.io/health-center:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


